# Numpy

In [1]:
# numpy : numerical python 
#       : Travis Oliphant in 2005
#       : function : high speed data processing which python cannot able to
#       : list[1,23,4,34,64] vs arr[1 2 33 4 65]
#       : 1D : [1 2 3 4 5] 0r 2D [[1 2 3 4 5][3 5 5 5 2]] or 3d [[[1 2 3 4][4 5 6 7]]] or ndim [[[[[]]]]]
#       : array oriented
#       : multidimention array, mathematical operation like laplace, fourier transformation, reshaping
#       : advantages : consume less memory, fast, easy to use
import numpy as np

In [3]:
#list to array
lst = [23,56,78,90,45]
print(lst)
arr = np.array(lst) #Creating 1D array
print(arr)

print(type(arr))

[23, 56, 78, 90, 45]
[23 56 78 90 45]
<class 'numpy.ndarray'>


In [10]:
#tuple to array
#list = []
#tuple = ()
#dictonary : {a : apple}
#set = {}
tpl = np.array((1,2,4,5,2,3))
print(tpl)
print(type(tpl))

[1 2 4 5 2 3]
<class 'numpy.ndarray'>


# Dimensions in array

In [11]:
arr = np.array(10)
print(arr)
print(type(arr))
print(arr.ndim) #to check array dimensions

10
<class 'numpy.ndarray'>
0


# 1D Array

In [12]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim,"D Array")

[1 2 3 4 5]
1 D Array


# 2D Array

In [13]:
arr = np.array([[2,4,6,8],[3,6,9,12]])
print(arr)
print(arr.ndim,"D Array")

[[ 2  4  6  8]
 [ 3  6  9 12]]
2 D Array


# 3D Array

In [13]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


# Multidimention Arrays

In [19]:
arr = np.array([2,4,6,8], ndmin = 2)
print(arr)
print(arr.ndim)

[[2 4 6 8]]
2


# Numpy Array Indexing

In [20]:
arr = np.array([1,2,3,4])
print(arr[2])

3


# 2D Array Access

In [14]:
arr = np.array([[1,2,3,4],[2,4,6,8]])
print(arr[0,3])

4


In [15]:
print(arr[1,3])

8


# 3D Array Access

In [16]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr[0,0,2], arr[0,1,1], arr[1,0,2], arr[1,1,2])

3 5 9 12


In [17]:
print(arr[0,0,2] + arr[0,1,1] + arr[1,0,2] + arr[1,1,2])

29


# Slicing of NumPy Array

In [19]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5]) #range slice

[2 3 4 5]


In [21]:
print(arr[1:8:2]) #step slicing
print(arr[::2])

[2 4 6 8]
[1 3 5 7]


# 2D array Slicing

In [22]:
arr = np.array([[2,4,6,8],[3,6,9,12]])
print(arr[0,0:2])

[2 4]


# Datatype of array

In [21]:
arr = np.array([1,-2,3,4,-5])
print(arr.dtype)

int32


In [22]:
arr = np.array([1,2.5,True,"char",5.1])
print(arr.dtype)

<U32


# Array with defined datatype

In [28]:
arr = np.array([1,2,3,4,5,6,7], dtype='I')
print(arr)
print(arr.dtype)

[1 2 3 4 5 6 7]
uint32


# Numpy Array Shape

In [30]:
arr = np.array([[1,2,3,4],[5,6,7,6]])
print(arr.shape)

(2, 4)


In [31]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)

(3, 4)


# Joining arrays

In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [35]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,22,33],[7,8,9]])

arr = np.concatenate((arr1,arr2), axis = 0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [ 7  8  9]]


# Splitting numpy array

In [34]:
arr = np.array([1,2,3,4,5,6,7,8])
split2 = np.array_split(arr,2)
split3 = np.array_split(arr,3)
split4 = np.array_split(arr,4)

print(split2,"\n",split3,"\n",split4)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])] 
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8])] 
 [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# Multidimention array to 1D array

In [35]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
arr1 = arr.ravel() #to convert multidimention array to 1D array
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Non repeating Values

In [36]:
arr = np.array([1,23,4,2,3,1,67,54,334,12,1,2,4,5,3,2,1])
uniq = np.unique(arr)
print(uniq)

[  1   2   3   4   5  12  23  54  67 334]


# Linspace

In [3]:
arr = np.linspace(1,15,10) # used to create an evenly spaced sequence in a specified interval.
print(arr)

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]


# Ones Zeros Empty Full

In [4]:
#ones : Creates an array of the specified shape and fills it with ones.
arr_ones = np.ones((3, 4), dtype=int)
print(arr_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
#zeros : Creates an array of the specified shape and fills it with zeros.
zeros_array = np.zeros((2, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#empty : Creates an array of the specified shape without initializing the elements to any particular values (the values are unpredictable and may vary).
empty_array = np.empty((2, 2))
print(empty_array)

[[2.12199579e-314 4.67296746e-307]
 [3.18178276e-321 3.79442416e-321]]


In [37]:
#full : Creates an array of the given shape and type, filled with a specified value.
full_array = np.full((2, 2), 10)
print(full_array)

[[10 10]
 [10 10]]


# Numpy Broadcasting

In [8]:
#It is a powerful feature that allows operations to be performed on arrays of different shapes and sizes.
#The smaller array is "broadcast" across the larger array so that they have compatible shapes for element-wise operations, without the need for explicit looping or copying of data.
#It is particularly useful when working with arrays of different dimensions and sizes.

#Rule 1: Dimensions of the arrays must be compatible.
#Rule 2: Sizes along a particular dimension must be the same or one of them must be 1.

a = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([10, 20, 30])

result = a + b

print(result)

[[11 22 33]
 [14 25 36]]
