In [1]:
import numpy as np

In [2]:
arr = np.array([2,4,6,8]) #Creating 1D array
print(arr)

print(type(arr))

[2 4 6 8]
<class 'numpy.ndarray'>


In [3]:
tpl = np.array((1,2,3,4,5,6,7,8))
print(tpl)
print(type(tpl))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


# Dimensions in array

In [4]:
arr = np.array(10)
print(arr)
print(type(arr))
print(arr.ndim) #to check array dimensions

10
<class 'numpy.ndarray'>
0


# 1D Array

In [5]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


# 2D Array

In [6]:
arr = np.array([[2,4,6,8],[3,6,9,12]])
print(arr)
print(arr.ndim)

[[ 2  4  6  8]
 [ 3  6  9 12]]
2


# 3D Array

In [13]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


# Multidimention Arrays

In [11]:
arr = np.array([2,4,6,8], ndmin = 4)
print(arr)
print(arr.ndim)

[[[[2 4 6 8]]]]
4


# Numpy Array Indexing

In [12]:
arr = np.array([1,2,3,4])
print(arr[2])

3


# 2D Array Access

In [14]:
arr = np.array([[1,2,3,4],[2,4,6,8]])
print(arr[0,3])

4


In [15]:
print(arr[1,3])

8


# 3D Array Access

In [16]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr[0,0,2], arr[0,1,1], arr[1,0,2], arr[1,1,2])

3 5 9 12


In [17]:
print(arr[0,0,2] + arr[0,1,1] + arr[1,0,2] + arr[1,1,2])

29


# Slicing of NumPy Array

In [19]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5]) #range slice

[2 3 4 5]


In [21]:
print(arr[1:8:2])
print(arr[::2])

[2 4 6 8]
[1 3 5 7]


# 2D array Slicing

In [22]:
arr = np.array([[2,4,6,8],[3,6,9,12]])
print(arr[0,0:2])

[2 4]


# Datatype of array

In [23]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [24]:
arr = np.array([1.2,2.5,3.8,4.0,5.1])
print(arr.dtype)

float64


# Array with defined datatype

In [25]:
arr = np.array([1,2,3,4,5,6,7], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7']
|S1


# Numpy Array Shape

In [26]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [27]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr.shape)

(1, 3, 4)


# Joining arrays

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [32]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[11,22,33],[7,8,9]])

arr = np.concatenate((arr1,arr2), axis = 0)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]
 [ 7  8  9]]


# Splitting numpy array

In [34]:
arr = np.array([1,2,3,4,5,6,7,8])
split2 = np.array_split(arr,2)
split3 = np.array_split(arr,3)
split4 = np.array_split(arr,4)

print(split2,"\n",split3,"\n",split4)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])] 
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8])] 
 [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# Multidimention array to 1D array

In [35]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
arr1 = arr.ravel() #to convert multidimention array to 1D array
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Non repeating Values

In [37]:
arr = np.array([1,23,4,2,3,1,67,54,334,12,1,2,4,5,3,2,1])
uniq = np.unique(arr)
print(uniq)

[  1   2   3   4   5  12  23  54  67 334]
